apiVersion: v1
kind: ConfigMap
metadata:
  name: zenoh-bridge-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: ros2-multi-robot-demo
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  gazebo-bridge.json5: |-
{{ .Files.Get "files/gazebo-bridge.json5" | indent 4 }}
  nav2-bridge.json5: |-
{{ .Files.Get "files/nav2-bridge.json5" | indent 4 }}
