apiVersion: v1
kind: ServiceAccount
metadata:
  name: ros2-demo
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/part-of: ros2-multi-robot-demo
    app.kubernetes.io/managed-by: {{ .Release.Service }}
